server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/user_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt:
      secret-key: {7DCdWTT4$I<GSWhqz]#PV8V1m.5*/Fh{:?KdtH6i%%o8#DSL~
